# copy_text.py — every word on the page, English and Thai, written by hand.
# Paragraph strings are HTML (only <span class="math">, <i>, <a> are used); everything else is escaped.
import json
import os

from copy_math import EN as MATH_EN, TH as MATH_TH

HERE = os.path.dirname(os.path.abspath(__file__))

PHOTOS = json.load(open(os.path.join(HERE, "credits.json")))

SOURCES = [
    ("Royal Institute dictionary (ORST): กระหนก, กนก, เหงา, ก้านขด, กระจัง, ประจำยาม, ลายรดน้ำ", "https://dictionary.orst.go.th/"),
    ("Thai Wikipedia: ลายกระหนก", "https://th.wikipedia.org/wiki/%E0%B8%A5%E0%B8%B2%E0%B8%A2%E0%B8%81%E0%B8%A3%E0%B8%B0%E0%B8%AB%E0%B8%99%E0%B8%81"),
    ("English Wikipedia: Kranok pattern", "https://en.wikipedia.org/wiki/Kranok_pattern"),
    ("Narit Vadhanabhu (2022), Fine & Applied Arts Journal, Thammasat 15(2)", "https://so05.tci-thaijo.org/index.php/fineartstujournal/article/view/261678"),
    ("Thairath (8 Oct 2020): instructors of the Royal Craftsmanship School", "https://www.thairath.co.th/scoop/1947195"),
    ("JitdraThanee: Thai pattern lessons 1–9", "https://jitdrathanee.com/studio/lesson05.htm"),
    ("Jiravansirikul & Areerungruang (2023), Silpakorn", "https://so01.tci-thaijo.org/index.php/AJA/article/view/266371"),
    ("Boonserm et al., Journal of Fine and Applied Arts, Thammasat", "https://so05.tci-thaijo.org/index.php/arts/article/download/256174/172596"),
    ("Thamwiset (2023), Analysis of Traditional Thai Pattern, KMUTT", "https://soad.kmutt.ac.th/wp-content/uploads/2023/12/2023INTC02.pdf"),
    ("Leelatrakul, Rimcharoen & Wachirahatpong (2014), Evolutionary Algorithm for Modelling Kranok Pattern, Burapha University", "https://buuir.buu.ac.th/jspui/bitstream/1234567890/17675/1/2569-538.pdf"),
    ("Toadithep & Itisarn (2008), Curve Fitting and Animated Drawing Thai Painting, ATCM", "https://atcm.mathandtech.org/ep2008/papers_full/2412008_15316.pdf"),
    ("Hobanthad et al. (2023), frieze and rosette groups at stone temples, Buriram Rajabhat", "https://ph02.tci-thaijo.org/index.php/scibru/article/view/249117"),
    ("Neti Phikroh (2024), lai kham, Journal of Buddhist Arts 7(1)", "https://so09.tci-thaijo.org/index.php/barts/article/view/4579"),
    ("Kajondet Niwyin (2022), lai kham at Wat Phra Singh and Lampang Luang, Journal of Thammawat 3(2)", "https://so09.tci-thaijo.org/index.php/tmwj/article/view/585"),
    ("Teerapong Jatuma (2025), Lanna stucco, Journal of Buddhist Arts 8(2)", "https://so09.tci-thaijo.org/index.php/barts/article/view/7722"),
    ("Patison Benyasuta (2022), Ayutthaya pulpits, Damrong Journal", "https://so01.tci-thaijo.org/index.php/damrong/article/view/254845"),
    ("Thai Wikipedia: ช่างสิบหมู่", "https://th.wikipedia.org/wiki/%E0%B8%8A%E0%B9%88%E0%B8%B2%E0%B8%87%E0%B8%AA%E0%B8%B4%E0%B8%9A%E0%B8%AB%E0%B8%A1%E0%B8%B9%E0%B9%88"),
    ("Thai Wikipedia: ลายรดน้ำ", "https://th.wikipedia.org/wiki/%E0%B8%A5%E0%B8%B2%E0%B8%A2%E0%B8%A3%E0%B8%94%E0%B8%99%E0%B9%89%E0%B8%B3"),
    ("Wikimedia Commons: every photograph, with its licence", "https://commons.wikimedia.org/"),
]

FRIEZE_EN = {
    "p1": ("Hop", "p1: slide only. Every copy faces the same way."),
    "p11g": ("Step", "p11g: slide, then flip over the middle line, like footprints."),
    "p1m1": ("Sidle", "p1m1: upright mirrors between neighbours."),
    "p11m": ("Jump", "p11m: one mirror along the middle line."),
    "p2": ("Spinning hop", "p2: half-turns between neighbours."),
    "p2mg": ("Spinning sidle", "p2mg: upright mirrors and footprints together."),
    "p2mm": ("Spinning jump", "p2mm: mirrors both ways."),
}
FRIEZE_TH = {
    "p1": ("เลื่อน", "p1 เลื่อนอย่างเดียว ทุกตัวหันทางเดียวกัน"),
    "p11g": ("ก้าวเดิน", "p11g เลื่อนแล้วพลิกข้ามเส้นกลาง เหมือนรอยเท้า"),
    "p1m1": ("กระจกตั้ง", "p1m1 มีกระจกตั้งคั่นระหว่างตัวที่อยู่ติดกัน"),
    "p11m": ("กระจกนอน", "p11m กระจกบานเดียววางตามเส้นกลาง"),
    "p2": ("หมุนครึ่งรอบ", "p2 หมุนครึ่งรอบระหว่างตัวที่อยู่ติดกัน"),
    "p2mg": ("กระจกตั้งกับรอยเท้า", "p2mg มีทั้งกระจกตั้งและการพลิกแบบรอยเท้า"),
    "p2mm": ("กระจกสองทาง", "p2mm กระจกทั้งแนวตั้งและแนวนอน"),
}

UI = {
    "en": {
        "lang_this": "EN", "lang_other": ("th/", "ไทย", "th"),
        "title": "Kranok, Drawn", "other_title": "กนก วาดด้วยคณิต",
        "desc": "Kranok, the flame of Thai ornament, drawn with math: the word, the curl, the one graph that bends a flame, the three-figure kranok, flames on flames, the coiled-stem scroll, seven ways to repeat a border, gold on black lacquer and Lanna lai kham. In English and Thai.",
        "card_alt": "Gold kranok flames and a coiled scroll on black lacquer",
        "hero_alt": "A gold scroll of kranok flames grows across black lacquer",
        "nav_label": "Sections",
        "nav": [("kranok", "Kranok"), ("curl", "Curl"), ("bend", "Bend"), ("three", "Three figures"), ("nest", "Nest"), ("scroll", "Scroll"), ("borders", "Borders"), ("draw", "Draw"), ("where", "Pictures"), ("words", "Words"), ("sources", "Sources")],
        "kicker": "Thai ornament, drawn with math",
        "lede": "Kranok is the flame at the root of Thai ornament: gold on the black lacquer of temple doors and scripture cabinets, carved into gables, worn on khon masks. Every flame on this page is drawn from one equation. Move your pointer near them and they lean away.",
        "cardline": "The flame of Thai ornament, drawn with math",
        "what_kick": "กระหนก · kranok",
        "what_h": "A word for gold, a pattern of flames",
        "what_p": [
            "The Royal Institute dictionary spells the pattern กระหนก, kranok: a kind of Thai ornament that is painted, gilded on lacquer, modelled or carved, in many kinds, such as flame kranok and coiled-stem kranok. It may also be written กนก. On its own, กนก (ka-nok) means gold, from Pali and Sanskrit <i>kanaka</i>. Thai Wikipedia reports Prince Naris's suggestion that the word first named gilt cabinets and passed to the pattern on them.",
            "Thai drawing has four categories: kranok, ornament; nari, human and divine figures; krabi, the monkeys and giants of the Ramakien; and kacha, animals real and from the Himmapan forest. Masters' books give five basic mother patterns (mae lai), the units repeated to build a design: krachang, phum khao bin, prachamyam, dao and kranok.",
            "Where the shape came from is argued. Thai Wikipedia traces it to the hang lai, the eel-tail figure, which comes from the look of a flame; one teacher adds snake tails. Art historian Santi Leksukhum is cited for an origin in Indian ornament of the Gupta period, and for the lotus as the source of the three-figure kranok. Thai sources list fern tips, vines, bamboo sheaths, cotton leaves and flames among the models for Thai pattern.",
            "The three-figure kranok, kranok sam tua, is the mother of all kranok, and where training starts: instructors at the Royal Craftsmanship School begin with it. The Office of Traditional Arts in the Fine Arts Department keeps the chang sip mu, the ten crafts: painting, carving, engraving, turning, casting, modelling, figure-making, lacquer, beaten metal and stucco.",
        ],
        "c_log": "Logarithmic", "c_arch": "Archimedean", "c_b": "Growth", "c_t": "Turns",
        "c_r1": "Each turn", "c_r2": "Angle to the centre line",
        "same_gap": "same gap", "changes": "changes",
        "b_turns": "Curl turns", "b_flick": "Flick at the tip", "b_teeth": "Notches", "b_depth": "Notch depth",
        "b_axis_y": "bending", "b_axis_x": "along the line", "b_eye": "eye", "b_tip": "tip",
        "three_kick": "กนกสามตัว · kranok sam tua",
        "three_h": "The three-figure kranok",
        "three_p": [
            "Three figures make the mother pattern: ตัวเหงา (tua ngao), the curl, lowest and in front; ตัวประกบ (tua prakop) or กาบ (kap), the sheath behind it; and ตัวยอด (tua yot), the tip. The Royal Institute dictionary gives เหงา as the name of the first kranok figure. Ngao also means lonely, and school lessons pun on its drooping curl.",
            "One recipe: an upright rectangle, 4 by 2, and its diagonal; the sheath in the bottom-left corner; a curve from the root into the head and up to the tip in the top-right corner; back down like a flame; split into three, notch them, add the inner lines. Another teacher uses a right triangle 3 tall and 2 wide, and lets the head bulge a little outside it, so the kranok looks alive.",
        ],
        "three_note": "Each figure here is one flame from the bending graph above, with a round belly around its curl. The teaching drawing is the first picture under Pictures.",
        "steps": ["Rough out an upright rectangle, twice as tall as it is wide, and draw the diagonal from bottom left to top right.", "The curl, tua ngao: lowest and in front, its head coiled like a snail shell.", "The sheath, tua prakop or kap: behind the curl, handing the line on.", "The tip, tua yot: the flame that rises to the top corner.", "Notches, bak, cut into the back of each figure.", "Inner lines, sai, drawn lighter, then gold on black lacquer."],
        "part_names": ["ตัวเหงา · curl", "ตัวประกบ · sheath", "ตัวยอด · tip"], "play": "Play", "pause": "Pause",
        "n_depth": "Levels", "n_ratio": "Size of each child", "n_count": "Flames", "n_gold": "Gold, if it went on forever",
        "s_grow": "Grow", "s_bones": "Lines only", "s_waves": "Waves", "s_turns": "Curl turns", "s_leaves": "Flames per curl",
        "frieze": FRIEZE_EN,
        "r_n": "Copies around the centre", "r_mirror": "Mirrors", "r_sym": "Symmetry", "r_moves": "moves",
        "own_hint": "Draw a line here",
        "o_seed": "Start one for me", "o_clear": "Clear", "o_save": "Save picture",
        "where_kick": "Where it lives",
        "where_h": "Gold on black",
        "where_p": [
            "Lai rot nam, water-washed pattern, is gold leaf laid on black lacquer and washed with water at the end, so the gold stays only where the design is. It covers doors, windows, walls and the cabinets that hold palm-leaf scriptures. Kranok also fills carved gables, khon masks and crowns, Bencharong porcelain, mother-of-pearl, and gilt stucco set with glass.",
            "For a gable, a door or a cabinet, the craftsman draws one half, traces it, flips the tracing and registers it on the centre line: mirror symmetry by hand.",
            "Artist กชวัช บูรณภิญโญ's exhibition ทำ-ลาย swapped kranok figures for bendy cartoon dogs, cats, ducks and birds. No frogs or toads: their round bodies cannot follow the mother pattern.",
        ],
        "lanna_h": "In the north",
        "lanna_p": [
            "In Lanna the gold is called kham. Lai kham is usually laid on red cinnabar, and at Wat Phra That Lampang Luang also on black lacquer. The gold goes on through a cut stencil, or is scratched, or both; the stencils carry kranok, flowers, geometric figures and praying deities. Wat Phra Singh in Chiang Mai has the Wihan Lai Kham, the hall of gilt pattern.",
            "Early Lanna stucco, as at Wat Pa Sak in Chiang Saen, is thick and layered, drawing on Hariphunchai, Bagan, Sukhothai, Khmer and Sri Lankan work. Ayutthaya pulpit makers later borrowed Lanna ornament, ngao curls at the corners among it.",
        ],
        "words_h": "Words",
        "words": [
            ("กระหนก · กนก", "kranok", "The flame-shaped pattern. กนก alone means gold."),
            ("ตัวเหงา", "tua ngao", "The curl: the first and lowest figure of a kranok."),
            ("ตัวประกบ · กาบ", "tua prakop · kap", "The sheath behind the curl."),
            ("ตัวยอด", "tua yot", "The tip, the flame that rises to the top."),
            ("บาก", "bak", "A notch cut into the back of a figure; บากเข้า curves in, บากออก curves out."),
            ("ไส้", "sai", "The inner line, drawn lighter than the outline."),
            ("แม่ลาย", "mae lai", "Mother pattern: the unit repeated in a row."),
            ("หางไหล", "hang lai", "The eel-tail figure, a flame-like stroke under the flame kranok."),
            ("กระหนกเปลว", "kranok plaeo", "Flame kranok, about six or seven notches a figure."),
            ("กระหนกใบเทศ", "kranok bai thet", "Kranok with a sheath, in and out notches, and inner lines."),
            ("ลายก้านขด", "lai kan khot", "The coiled-stem scroll."),
            ("ลายกระจัง", "lai krachang", "A triangular leaf pattern set in rows along edges."),
            ("ประจำยาม", "prachamyam", "A four-petal flower set at intervals between other patterns."),
            ("ลายหน้ากระดาน", "lai na kradan", "The running band between lotus mouldings."),
            ("ลายรดน้ำ", "lai rot nam", "Gold leaf on black lacquer, washed with water."),
            ("ลายคำ", "lai kham", "Lanna gilt pattern, often on red."),
            ("ช่างสิบหมู่", "chang sip mu", "The ten crafts; also the Office of Traditional Arts."),
        ],
        "src_h": "Sources",
        "src_p": "Facts come from these; the drawing method, the spiral fit and the recursion are this page's own. Thai researchers have built kranok from Bézier curves (Silpakorn 2008, Burapha 2014) and modelled each notch as two S-curves (KMUTT 2023).",
        "foot": "Text CC BY 4.0, NaNoBotCo. Code MIT. Photographs keep their own licences.",
    },
    "th": {
        "lang_this": "ไทย", "lang_other": ("../", "EN", "en"),
        "title": "กนก วาดด้วยคณิต", "other_title": "Kranok, Drawn",
        "desc": "กระหนก เปลวไฟแห่งลายไทย วาดด้วยคณิต ตั้งแต่คำ ตัวเหงา กราฟเดียวที่ดัดเปลวทั้งตัว กนกสามตัว กนกซ้อนกนก ลายก้านขด เจ็ดวิธีซ้ำลายหน้ากระดาน ลายรดน้ำ และลายคำล้านนา ภาษาไทยและอังกฤษ",
        "card_alt": "เปลวกนกสีทองกับลายก้านขดบนพื้นรักสีดำ",
        "hero_alt": "ลายก้านขดเปลวกนกสีทองค่อย ๆ งอกบนพื้นรักสีดำ",
        "nav_label": "หัวข้อ",
        "nav": [("kranok", "กระหนก"), ("curl", "ตัวเหงา"), ("bend", "ความโค้ง"), ("three", "กนกสามตัว"), ("nest", "ซ้อน"), ("scroll", "ก้านขด"), ("borders", "ลายขอบ"), ("draw", "วาด"), ("where", "ภาพ"), ("words", "ศัพท์"), ("sources", "ที่มา")],
        "kicker": "ลายไทย วาดด้วยคณิต",
        "lede": "กระหนกคือเปลวไฟที่เป็นรากของลายไทย เป็นทองบนพื้นรักดำของบานประตูโบสถ์และตู้พระธรรม จำหลักอยู่บนหน้าบัน และอยู่บนหัวโขน ทุกเปลวในหน้านี้วาดจากสมการเดียว ลองเลื่อนเมาส์เข้าใกล้ เปลวจะเอนหนี",
        "cardline": "เปลวไฟแห่งลายไทย วาดด้วยคณิต",
        "what_kick": "กระหนก",
        "what_h": "คำที่แปลว่าทอง ลายที่เป็นเปลวไฟ",
        "what_p": [
            "พจนานุกรมฉบับราชบัณฑิตยสถานเขียนชื่อลายนี้ว่า กระหนก คือลายไทยประเภทหนึ่ง ใช้ผูกเขียนเป็นลวดลาย มีทั้งระบายสี ปิดทองรดน้ำ ปั้น หรือแกะสลัก มีหลายแบบ เช่น กระหนกเปลว กระหนกก้านขด และเขียนเป็น กนก ก็มี ส่วนคำว่า กนก (กะ-หนก) เมื่ออยู่ลำพังแปลว่าทองคำ มาจากบาลีและสันสกฤต <i>kanaka</i> วิกิพีเดียภาษาไทยอ้างว่าสมเด็จฯ เจ้าฟ้ากรมพระยานริศรานุวัดติวงศ์ทรงสันนิษฐานว่า คำนี้เดิมใช้เรียกตู้ลายทอง แล้วจึงมาเรียกลายบนตู้นั้น",
            "งานเขียนไทยแบ่งเป็นสี่หมวด คือ หมวดกระหนก ได้แก่ลวดลาย หมวดนารี ได้แก่ภาพมนุษย์และเทวดา หมวดกระบี่ ได้แก่ลิงและยักษ์ในรามเกียรติ์ และหมวดคชะ ได้แก่สัตว์ทั้งจริงและในป่าหิมพานต์ ตำราของครูช่างให้แม่ลายพื้นฐานห้าแบบ คือ แม่ลายกระจัง พุ่มข้าวบิณฑ์ ประจำยาม ดาว และกระหนก",
            "ที่มาของรูปทรงยังเป็นที่ถกเถียง วิกิพีเดียภาษาไทยว่าต้นแบบมาจากหางไหล ซึ่งมาจากลักษณะของเปลวไฟ ครูบางท่านเพิ่มหางงูเข้าไปด้วย อาจารย์สันติ เล็กสุขุม ถูกอ้างว่าเห็นที่มาในลวดลายอินเดียสมัยคุปตะ และเห็นดอกบัวเป็นต้นแบบของกระหนกสามตัว แหล่งข้อมูลไทยยังนับยอดผักกูด เถาวัลย์ กาบไผ่ ใบฝ้ายเทศ และเปลวไฟ เป็นแบบของลายไทย",
            "กระหนกสามตัวเป็นแม่ลาย ถือเป็นแม่แบบของกระหนกทั้งหลาย และเป็นจุดเริ่มของการเรียน ครูโรงเรียนช่างฝีมือในวังเริ่มสอนจากลายนี้ สำนักช่างสิบหมู่ กรมศิลปากร ดูแลช่างสิบหมู่ ได้แก่ ช่างเขียน ช่างแกะ ช่างสลัก ช่างกลึง ช่างหล่อ ช่างปั้น ช่างหุ่น ช่างรัก ช่างบุ และช่างปูน",
        ],
        "c_log": "ลอการิทึม", "c_arch": "อาร์คิมิดีส", "c_b": "อัตราขยาย", "c_t": "จำนวนรอบ",
        "c_r1": "แต่ละรอบ", "c_r2": "มุมกับเส้นจากจุดศูนย์กลาง",
        "same_gap": "ระยะเท่าเดิม", "changes": "เปลี่ยนไป",
        "b_turns": "จำนวนรอบของขด", "b_flick": "การสะบัดปลาย", "b_teeth": "จำนวนบาก", "b_depth": "ความลึกของบาก",
        "b_axis_y": "ความโค้ง", "b_axis_x": "ไปตามเส้น", "b_eye": "ตาขด", "b_tip": "ยอด",
        "three_kick": "กนกสามตัว",
        "three_h": "กระหนกสามตัว",
        "three_p": [
            "แม่ลายนี้มีสามตัว ตัวเหงา คือตัวขด อยู่ล่างสุดและอยู่หน้า ตัวประกบหรือกาบ อยู่หลังตัวเหงา และตัวยอด คือเปลวที่ปลาย พจนานุกรมฉบับราชบัณฑิตยสถานให้ความหมายของ เหงา ว่าชื่อลายกระหนกตัวแรก บทเรียนในโรงเรียนเล่นคำว่าตัวเหงาก้มหน้าดูเศร้า ๆ เหงา ๆ",
            "สูตรหนึ่ง: ร่างสี่เหลี่ยมผืนผ้าตั้งสัดส่วน 4 ต่อ 2 ลากเส้นทแยง วางกาบไว้มุมล่างซ้าย ลากเส้นจากโคนเข้าหัว แล้วขึ้นไปถึงยอดที่มุมบนขวา ลากกลับลงมาเป็นเปลว แบ่งเป็นสามตัว บาก แล้วใส่ไส้ ครูอีกท่านใช้สามเหลี่ยมมุมฉากสูง 3 กว้าง 2 และให้หัวกระหนกล้นออกนอกกรอบเล็กน้อย กระหนกจะดูมีชีวิต",
        ],
        "three_note": "แต่ละตัวในภาพนี้คือเปลวหนึ่งตัวจากกราฟความโค้งข้างบน มีท้องกลมล้อมขด ภาพลายเส้นต้นแบบอยู่เป็นภาพแรกในหัวข้อภาพ",
        "steps": ["ร่างสี่เหลี่ยมผืนผ้าตั้ง สูงเป็นสองเท่าของความกว้าง แล้วลากเส้นทแยงจากมุมล่างซ้ายไปมุมบนขวา", "ตัวเหงา อยู่ล่างสุดและอยู่หน้า หัวขดเหมือนก้นหอย", "ตัวประกบหรือกาบ อยู่หลังตัวเหงา ส่งเส้นต่อขึ้นไป", "ตัวยอด เปลวที่พุ่งขึ้นไปถึงมุมบน", "บากบนหลังของแต่ละตัว", "เส้นไส้ เขียนให้อ่อนกว่าเส้นรูป แล้วปิดทองบนพื้นรักดำ"],
        "part_names": ["ตัวเหงา", "ตัวประกบ · กาบ", "ตัวยอด"], "play": "เล่น", "pause": "หยุด",
        "n_depth": "จำนวนชั้น", "n_ratio": "ขนาดของตัวลูก", "n_count": "จำนวนเปลว", "n_gold": "ทองทั้งหมด ถ้าซ้อนไปไม่สิ้นสุด",
        "s_grow": "ให้งอก", "s_bones": "เฉพาะเส้น", "s_waves": "จำนวนคลื่น", "s_turns": "จำนวนรอบของขด", "s_leaves": "เปลวต่อขด",
        "frieze": FRIEZE_TH,
        "r_n": "จำนวนตัวรอบจุดศูนย์กลาง", "r_mirror": "กระจก", "r_sym": "สมมาตร", "r_moves": "แบบ",
        "own_hint": "ลากเส้นตรงนี้",
        "o_seed": "เริ่มให้หนึ่งเส้น", "o_clear": "ล้าง", "o_save": "บันทึกภาพ",
        "where_kick": "อยู่ที่ไหน",
        "where_h": "ทองบนรักดำ",
        "where_p": [
            "ลายรดน้ำ คือการปิดทองคำเปลวบนพื้นลงรักสีดำ แล้วรดน้ำในขั้นสุดท้าย ทองจึงติดอยู่เฉพาะตรงที่เป็นลาย พบบนบานประตู หน้าต่าง ผนัง และตู้พระธรรมที่เก็บคัมภีร์ใบลาน กระหนกยังเต็มอยู่บนหน้าบันจำหลัก หัวโขนและเครื่องศิราภรณ์ เครื่องเบญจรงค์ งานประดับมุก และปูนปั้นปิดทองประดับกระจก",
            "สำหรับหน้าบัน บานประตู หรือตู้ ช่างเขียนลายครึ่งเดียว ลอกลงกระดาษไข พลิกกระดาษ แล้วทาบให้ตรงเส้นกลาง ได้ความสมมาตรแบบกระจกด้วยมือ",
            "นิทรรศการ ทำ-ลาย ของศิลปิน กชวัช บูรณภิญโญ เปลี่ยนตัวกระหนกเป็นหมา แมว เป็ด และนกการ์ตูนที่ตัวงอได้ แต่ไม่มีกบหรือคางคก เพราะตัวกลม ๆ ไปตามแม่ลายไม่ได้",
        ],
        "lanna_h": "ทางเหนือ",
        "lanna_p": [
            "ในล้านนาเรียกทองว่า คำ ลายคำมักลงบนพื้นชาดสีแดง และที่วัดพระธาตุลำปางหลวงลงบนพื้นรักดำด้วย ทองติดลงผ่านแม่พิมพ์ฉลุ หรือขูดลาย หรือทั้งสองอย่าง แม่พิมพ์มีลายกระหนก ลายดอกไม้ ลายเรขาคณิต และเทพนม วัดพระสิงห์ เชียงใหม่ มีวิหารลายคำ",
            "ปูนปั้นล้านนายุคแรก เช่นที่วัดป่าสัก เชียงแสน หนาและซ้อนหลายชั้น ได้อิทธิพลจากหริภุญชัย พุกาม สุโขทัย เขมร และลังกา ต่อมาช่างธรรมาสน์อยุธยายืมลายล้านนาไปใช้ รวมถึงตัวเหงาที่มุม",
        ],
        "words_h": "ศัพท์",
        "words": [
            ("กระหนก · กนก", "kranok", "ลายรูปเปลวไฟ กนก คำเดียวแปลว่าทอง"),
            ("ตัวเหงา", "tua ngao", "ตัวขด ตัวแรกและตัวล่างสุดของกระหนก"),
            ("ตัวประกบ · กาบ", "tua prakop · kap", "ตัวที่อยู่หลังตัวเหงา"),
            ("ตัวยอด", "tua yot", "เปลวที่พุ่งขึ้นไปถึงยอด"),
            ("บาก", "bak", "รอยบากบนหลังตัวลาย มีบากเข้าและบากออก"),
            ("ไส้", "sai", "เส้นใน เขียนอ่อนกว่าเส้นรูป"),
            ("แม่ลาย", "mae lai", "ลายตอนที่เป็นประธาน ซ้ำ ๆ กันเป็นแถว"),
            ("หางไหล", "hang lai", "ลายหางปลาไหล เส้นคล้ายเปลวที่เป็นโครงของกระหนกเปลว"),
            ("กระหนกเปลว", "kranok plaeo", "กระหนกที่ปลายสะบัดเหมือนเปลว ราวหกถึงเจ็ดบากต่อตัว"),
            ("กระหนกใบเทศ", "kranok bai thet", "กระหนกที่มีกาบ บากเข้าบากออก และไส้"),
            ("ลายก้านขด", "lai kan khot", "ลายที่เขียนเป็นก้านขดไปขดมา"),
            ("ลายกระจัง", "lai krachang", "ลายในรูปสามเหลี่ยม เรียงตามขอบ"),
            ("ประจำยาม", "prachamyam", "ดอกไม้สี่กลีบ วางเป็นระยะคั่นลายอื่น"),
            ("ลายหน้ากระดาน", "lai na kradan", "ลายแถบยาวบนพื้นตั้งระหว่างบัว"),
            ("ลายรดน้ำ", "lai rot nam", "ทองบนพื้นรักดำ รดน้ำในขั้นสุดท้าย"),
            ("ลายคำ", "lai kham", "ลายทองล้านนา มักลงบนพื้นแดง"),
            ("ช่างสิบหมู่", "chang sip mu", "ช่างสิบประเภท และชื่อสำนักในกรมศิลปากร"),
        ],
        "src_h": "ที่มา",
        "src_p": "ข้อเท็จจริงมาจากแหล่งเหล่านี้ ส่วนวิธีวาด การเทียบกับเกลียว และการซ้อนกนก เป็นของหน้านี้เอง นักวิจัยไทยเคยสร้างกระหนกด้วยเส้นโค้งเบซิเย (ศิลปากร 2551 บูรพา 2557) และจำลองบากแต่ละบากเป็นเส้นโค้งรูปตัว S สองเส้น (มจธ. 2566)",
        "foot": "ข้อความ CC BY 4.0 NaNoBotCo โค้ด MIT ภาพถ่ายใช้สัญญาอนุญาตของแต่ละภาพ",
    },
}

UI["en"].update(MATH_EN)
UI["th"].update(MATH_TH)
